### ISSUE TITLE
Add to poi's description

### ISSUE THREAD

**Issue by wafer-li** [ruiii/plugin-Hairstrength#15]
感觉这个插件还是蛮重要的，建议将这个插件加到 poi 的 `README` 里面。

**Comment by ruiii** [comment]
最近在做个 “你知道吗” 的东西
打算放本体里

**Comment by ruiii** [comment]
。。怀疑我傻了 现在才发现看错issue 我先自杀一会儿
等秃秃再稳定一些吧
目前还有功能没有完善
