### ISSUE TITLE
重启poi后记录为空，但是记录存在

### ISSUE THREAD

**Issue by dkwingsmt** [ruiii/plugin-Hairstrength#29]
类似的汇报收到过好几起了
![image](https://cloud.githubusercontent.com/assets/1596656/15199585/1a069a0a-17a5-11e6-9787-764cdec018e0.png)
他的数据文件夹附在最后了
[hairstrength.zip](https://github.com/ruiii/plugin-Hairstrength/files/260375/hairstrength.zip)

**Comment by Ayaphis** [comment]
https://github.com/ruiii/plugin-Hairstrength/pull/30/commits/3cbfc8e85f6cddc284174162a53a406fc773ace8

hope this fix will be help

**Comment by ruiii** [comment]
不懂啊。。怎么突然出现这种情况
一脸蒙蔽。。
这几天还没有时间处理
